# Search
GET http://localhost:3000/api/search?query=Учим HTTP/1.1

###

# Categories list
GET http://localhost:3000/api/categories HTTP/1.1

###

# All articles
GET http://localhost:3000/api/articles HTTP/1.1

###

# Article by id
GET http://localhost:3000/api/articles/1 HTTP/1.1

###

# Delete article by id
DELETE http://localhost:3000/api/articles/10 HTTP/1.1

###

# Add new article
POST http://localhost:3000/api/articles HTTP/1.1
Content-Type: application/json

{
  "title": "Новый заголовок статьи. Новый заголовок статьи.",
  "image": null,
  "createdDate": "2021-01-10T14:12:47.445Z",
  "announce": "Новый анонс статьи. Новый анонс статьи.",
  "fullText": "Новый текст",
  "categories": [1]
}

###

# Update article
PUT http://localhost:3000/api/articles/6 HTTP/1.1
Content-Type: application/json

{
  "title": "Новый-новый заголовок статьи. Новый-новый заголовок статьи.",
  "image": null,
  "createdDate": "2021-01-10T14:12:47.445Z",
  "announce": "Новый-новый анонс статьи. Новый-новый анонс статьи.",
  "fullText": "Новый-новый анонс статьи. Новый-новый анонс статьи.",
  "categories": [1, 2]
}

###

# Comments list

GET http://localhost:3000/api/articles/1/comments HTTP/1.1

###

# Add comment

POST http://localhost:3000/api/articles/1/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Новый комментарий. Новый комментарий."
}

###

# Delete comment

DELETE http://localhost:3000/api/articles/1/comments/24 HTTP/1.1
